### PR TITLE
Add an option to skip documents during validation

### LINKED ISSUE #191: Add option to suppress messages for selected documents
We're developing multiple documents/levels and are transitioning certain ones under formal change control.

It would be helpful if we could run the `doorstop` validation, but suppress the `ERROR`|`WARNING`|`INFO` for select documents.

Example:

```
Feature List [FL]
  |
  -- System Requirements Specification [SYSRS]
    |
    ---- Software High-Level Requirements [SWHLR]
    |
    ---- Hardware High-Level Requirements [HWHLR]
```

The `FL` and `SYSRS` are reviewed and approved by the customer. Work is beginning on `SWHLR` and `HWHLR`. We need to track/fix `FL`|`SYSRS`, but `SWHLR`|`HWHLR` are a little more free-flowing.

I'd like to run `$ doorstop` from my `Makefile` and CI and only generate errors when `FL` and/or `SYSRS` are affected. Also since `FL`|`SYSRS` are held to a higher level of integrity, I'm also elevating `WARNING` -> `ERROR`.

An example command line call could be:
`$ doorstop --no-level-check --error-all --suppress SWHLR --suppress HWHLR`

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/8113433-add-option-to-suppress-messages-for-selected-documents?utm_campaign=plugin&utm_content=tracker%2F537563&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F537563&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jacebrowning**
Fixes #191

### CODE REVIEW

**Comment by robertberrington** [comment]
Looks like it's working pretty good. There are few residual messages I wonder if they should also be suppressed:

**Example 1:**
SYSRS-0680 has children, but only MEHLR is under change control, but should NOT link to SYSRS-0680 (a Software slanted requirement)
```
$ doorstop --skip CLHLR --skip HWHLR --skip SWHLR
...
WARNING: SYSRS: SYSRS-0680: no links from child document: CLHLR
WARNING: SYSRS: SYSRS-0680: no links from child document: HWHLR
WARNING: SYSRS: SYSRS-0680: no links from child document: MEHLR
WARNING: SYSRS: SYSRS-0680: no links from child document: SWHLR
...
```
Adding `--no-child-check` suppresses ALL missing parent -> child links. Is there a middle ground where we can suppress this for "skipped" documents?

Also, without making a "dummy" MEHLR item to point blindly at intentionally un-developed SYSRS, how do I flag these relationship in doorstop so I can elevate `WARNING` -> `ERROR` as part of my CI once I'm under change control?

**Example 2:**
SWHLR-0093 is `active = FALSE` and points to a SYSRS item. Perhaps this should be suppressed for documents skipped?
```
$ doorstop --skip CLHLR --skip HWHLR --skip SWHLR
...
WARNING: no item with UID: SWHLR-0093
...
```

So ... other than those two observations ... looks great!

Perhaps consider making the 1st example above a separate issue ... I think that one may be a large "unaddressed" issue we haven't wrestled with enough.

**Comment by robertberrington** [comment]
@jacebrowning ... I was talking with Javis concerning the issue regarding "Parent-Child" links (or absence).

What about adding a property like `item.allocation`. This could be a space-delimited space to list the `child` document `ID`'s that should be linked. This is a "design-step" following the development of the "requirement", but would be a way to validate that "children" requirements exist where they are expected.

In a current project we are setting up a design-review meeting to discuss each requirements allocation to HW | SW | CL | ME. This is also meant to make sure we've addressed all the requirements in the design. We could just as easily populate this field directly in `doorstop` with a list of ID's where lower level requirements are expected.

**Comment by jacebrowning** [comment]
@robertberrington This commit should fix your **Example 1**. I agree these "reverse lookup" warnings should be suppressed if the document is skipped.

I think that **Example 2** should always be a warning even if a document is skipped. This warning is telling you that you're linking to an item that essentially doesn't exist.

Regarding your second comment, if this is still desirable after the above commit, please submit a separate issue to discuss further.

**Comment by robertberrington** [comment]
@jacebrowning I tested the commit: `1fab5bbbb14b71422450955eec8282a5b9fddf50`

I'm still getting the "reverse look-up" warnings for skipped documents.

```
$ doorstop --no-level-check --skip HWHLR --skip SWHLR --skip CLHLR
...
WARNING: SYSRS: SYSRS-0680: no links from child document: CLHLR
WARNING: SYSRS: SYSRS-0680: no links from child document: HWHLR
WARNING: SYSRS: SYSRS-0680: no links from child document: MEHLR
WARNING: SYSRS: SYSRS-0680: no links from child document: SWHLR
...
```

I think since `MEHLR` is not skipped, the `WARNING: SYSRS: SYSRS-0680: no links from child document: MEHLR` is the only one that should remain.

Also, just to double-check your language/thinking:
>
I think that Example 2 should always be a warning even if a document is skipped. This warning is telling you that you're linking to an item that essentially doesn't exist.
>
Just to clarify, I'm getting a warning on the child that is `active=FALSE` ... if the child is essentially turned OFF, should the warning be suppressed? I could see a nuance to the validation where you will throw a `WARNING: ... no links from child document ...` if there are no `active=TRUE` items linked.

The way you worded your justification, I agree ... if the parent is `active=FALSE`, you should throw a `WARNING` for the child that it is linking to an turned-OFF/inactive/deleted requirement.

I'm wondering if the `no links from child document` warning is suppressed if the a Parent <- Child link exists, but the Child is `active=FALSE`?

By the way, I really like the `active=FALSE` feature. It allows me to turn requirements ON/OFF as part of feature planning so that I can maintain a main-line of development and manage `active` with a flag instead of a [repo]-delete.

**Comment by jacebrowning** [comment]
@robertberrington Let me know if that looks good for your **Example 1**.

I think you'll find that in some of your **Example 2** cases, it's not actually causing your builds to fail, but just printing a warning. Either way, I think that should be a separate discussion.

**Comment by robertberrington** [comment]
The works well. The only issue I have is when I elevate `WARNING` to `ERROR` using the `--error-all` flag, the `WARNING: SYSRS: SYSRS-0615: no links from child document: MEHLR` causes the target to fail.

Since there are other documents in development, they will eventually cover these SYSRS items.

Would it make sense that the `ERROR: SYSRS: SYSRS-0615: no links from child document: MEHLR` would remain a `WARNING` when the `--error-all` is used ... like `WARNING: no item with UID: SWHLR-0057` (where SWHLR is `active=FALSE`, but it links to an active SYSRS)?

Frankly, I like that a `WARNING` -> `ERROR` is thrown in this case, except I've looked at all these instances and know they are intentional.

The feature requested in #194 would potentially address this.

**Pull request merged**
