### PR TITLE
Jmac/html navigation 3

### PR DESCRIPTION
**Pull request by jmacarthur**
Succeeds #264. As per the original, this adds some extra navigation to the web front end and switches over to using Bottle's templates rather than string.template which gives us a bit more flexibility. It's not perfect yet (inline images and the navigation bar are broken) but should be an improvement.

Updated to allow relative URLs for .css & .js files again for static web pages, and adds the previously missing general.css file.

### CODE REVIEW

**Comment by jacebrowning** [comment]
I'm going to merge in `master` to get the review app tooling I just added. This will let us browse the generated HTML on PRs.

**Comment by jmacarthur** [comment]
That's a new one on me. Was that with the bottle server or static pages?

**Comment by jacebrowning** [comment]
I see the same behavior with both the server and the static pages.

**Comment by jmacarthur** [comment]
It looks like `$("#main a").attr("target", "parent");` in sidebar.tpl's javascript. I get the same behaviour in the develop branch.

**Comment by jmacarthur** [comment]
Thanks for reviewing!

**Pull request merged**
